[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "A 'proof' of bandwidth, cpu and storage for nodes in a decentralised network."
documentation = "https://docs.rs/resource_proof"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "resource_proof"
readme = "README.md"
repository = "https://github.com/maidsafe/resource_proof"
version = "0.5.0"

[dependencies]
clap = "~2.25.1"
rand = "~0.3.15"
tiny-keccak = "~1.3.0"

[target."cfg(unix)".dependencies]
termion = "~1.4.0"
